variable "db_allocated_storage" {
  description = "DB Storage Capacity in GiB"
  type        = number
  default     = 10
}
variable "db_max_allocated_storage" {
  description = "Max DB Storage Capacity in GiB"
  type        = number
  default     = 20 #Max free trial capacity
}
variable "db_engine" {
  description = "DB engine"
  type        = string
  default     = "postgres"
}
variable "db_engine_version" {
  description = "DB engine version"
  type        = string
  default     = "14.2"
}
variable "db_instance_class" {
  description = "DB instance class"
  type        = string
  default     = "db.t3.micro"
}
variable "db_name" {
  description = "DB name"
  type        = string
  default     = "psqldb"
}
variable "db_username" {
  description = "DB Root username"
  type        = string
  default     = "postgres"
}
variable "db_parameter_group_name" {
  description = "DB parameter group name"
  type        = string
  default     = "default.postgres14"
}
variable "db_skip_final_snapshot" {
  description = "Skip final snapshot"
  type        = bool
  default     = true
}
variable "db_iam_authentication_enabled" {
  description = "Enable DB authentication using IAM users"
  type        = bool
  default     = true
}
variable "db_subnet_group_name" {
  description = "DB private subnet name"
  type        = string
  default     = "main"
}
variable "db_subnet_group_id" {
  description = "id of private subnets"
  type        = list(string)
}
variable "db_tags" {
  description = "DB tags"
  type        = map(any)
  default = {
    Name = "main"
  }
}
variable "db_root_password_length" {
  description = "Length of autogenerated root password"
  type        = number
  default     = 16
}
variable "db_identifier" {
  description = "DB identifier"
  type        = string
  default     = "db-instance"
}

variable "db_port" {
  description = "DB Port"
  default     = "5432"
}

variable "vpc_id" {
  description = "VPC ID"
}

#variable "default_rds_segurity_group" {
#  description = "DB SG"
#  type        = string
#}